insert into departments (department_name, Manager_id) values ('Deutsche Bank AG', 11);
insert into departments (department_name, Manager_id) values ('Perficient, Inc.', 22);
insert into departments (department_name, Manager_id) values ('The First of Long Island Corporation', 103);
insert into departments (department_name, Manager_id) values ('Consolidated Edison Inc', 74);
insert into departments (department_name, Manager_id) values ('Frontier Communications Corporation', 35);
insert into departments (department_name, Manager_id) values ('Public Storage', 46);
insert into departments (department_name, Manager_id) values ('PC Connection, Inc.', 97);
insert into departments (department_name, Manager_id) values ('Pathfinder Bancorp, Inc.', 8);
insert into departments (department_name, Manager_id) values ('DineEquity, Inc', 19);
insert into departments (department_name, Manager_id) values ('Alkermes plc', 104);
insert into departments (department_name, Manager_id) values ('Kaiser Aluminum Corporation', 411);
insert into departments (department_name, Manager_id) values ('Farmer Brothers Company', 128);
insert into departments (department_name, Manager_id) values ('Embotelladora Andina S.A.', 173);
insert into departments (department_name, Manager_id) values ('Orbotech Ltd.', 714);
insert into departments (department_name, Manager_id) values ('Sunesis Pharmaceuticals, Inc.', 315);
insert into departments (department_name, Manager_id) values ('Avenue Therapeutics, Inc.', 16);
insert into departments (department_name, Manager_id) values ('Janus Henderson SG Global Quality Income ETF', 217);
insert into departments (department_name, Manager_id) values ('Blackrock Defined Opportunity Credit Trust', 118);
insert into departments (department_name, Manager_id) values ('Invesco Pennsylvania Value Municipal Income Trust', 190);
insert into departments (department_name, Manager_id) values ('Oxford Lane Capital Corp.', 820);
